fix: deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,17 +63,17 @@ jobs:
               
               if pgrep -f "start-bot" > /dev/null; then
                 echo "Stopping the existing application..."
-                pkill -f "start-bot" || { echo "Failed to stop the application"; exit 1; }
+                pkill -f "start-bot" || echo "Failed to stop the application, continuing with deployment."
               else
                 echo "No running application found."
               fi
 
+              git pull origin stage-dev || { echo "Git pull failed"; exit 1; }
 
-              git pull origin stage-dev
-
-              go build -o start-bot ./cmd/bot/main.go
+              echo "Building the new version..."
+              go build -o start-bot ./cmd/bot/main.go || { echo "Build failed"; exit 1; }
 
               echo "Starting the new version..."
-              nohup ./start-bot > app.log 2>&1 &
+              nohup ./start-bot > app.log 2>&1 & echo $! > start-bot.pid || { echo "Failed to start the application"; exit 1; }
 
               echo "Deploy complete!"
